# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --no-build --configuration Release --verbosity detailed
    - name: Push Nuget Package
      run: |
        ls -la bin/Release/
        PACKAGE=$(ls bin/Release/*.nupkg | head -n 1)
        echo "Pushing package: $PACKAGE"
        dotnet nuget push "$PACKAGE" --source "https://nuget.pkg.github.com/kseretis/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
    - name: Clean Output Directory
      run: rm -rf bin/Release/net8.0/


